dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
dotenv: .env
networks:
  local-ganache:
    verify: False
  development:
    verify: False
  sepolia:
    eth_usd_pricefeed : "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    verify: True
  mainnet-fork-dev:
    eth_usd_pricefeed : "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
wallets:
  from_key : ${PRIVATE_KEY}

